version: '3'
networks:
  infra:
    external: false
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.1.0/24

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - GITEA__repository__ROOT=/data/git/gitea-repositories
      - GITEA__server__HTTP_PORT=3000
      - GITEA__server__ROOT_URL=http://localhost:3000
      - GITEA__webhook__ALLOWED_HOST_LIST=jenkins, 172.19.1.11
    restart: always
    networks:
      infra:
        ipv4_address: 172.19.1.10
    volumes:
      - ./gitea-files:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
      - 222:22
    depends_on:
      - db

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    restart: always
    privileged: true
    user: root
    ports:
      - 2140:8080
      - 50000:50000
    container_name: jenkins
    networks:
      infra:
        ipv4_address: 172.19.1.11
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins-files:/var/jenkins_home
    depends_on:
      - gitea
    
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
    networks:
      - infra
    volumes:
      - ./mysql-files:/var/lib/mysql
    ports:
      - 3306:3306
